version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://amir:amir1234@flask_db:5432/postgres"
    depends_on:
      - flask_db

  flask_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=amir1234
      - POSTGRES_USER=amir
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/app/postgres

volumes:
  pgdata:
  postgres-data:
networks:
  pgnet:
