"""empty message

Revision ID: 529a2a867eee
Revises: 
Create Date: 2023-10-20 15:57:38.262708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '529a2a867eee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=True),
    sa.Column('logo', sa.String(length=80), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Enum('Introduction', 'Presentation', 'Negotiation', 'Contract', 'Deploy', 'Test', 'Report', 'Termination', 'Active', name='customerstate'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('Introduction', 'Presentation', 'Negotiation', 'Contract', 'Deploy', 'Test', 'Report', 'Termination', 'Active', name='customerstate'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('customers')
    # ### end Alembic commands ###
